version: '3.8'

services:
  front_despacho:
    # 1. Construye la imagen local usando el Dockerfile multi-stage del Frontend
    build:
      context: .
      dockerfile: Dockerfile
    container_name: front_despacho_container
    restart: always

    # 2. Expone el puerto público estándar (80) hacia internet
    ports:
      - "80:80"

    # 3. Variables de entorno
    environment:
      - NODE_ENV=production

    # 4. Red interna
    networks:
      - app-network

networks:
  app-network:
    driver: bridge