server {
    listen 80;
    server_name localhost;

    # Sirve los archivos estáticos de React
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # REVERSE PROXY: Redirige las peticiones de la API al Backend
    # ➡️ QUITAMOS la barra diagonal del final de "/api" para que machee limpio
    location /api {
        # ➡️ IMPORTANTE: Quitamos la barra del final de la IP.
        # De esta forma Nginx pasa la ruta exacta (/api/v1/despachos) sin recortar nada.
        proxy_pass http://10.0.134.21:8085;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}