server {
    listen 80;
    server_name localhost;

    # Archivos estáticos del frontend de React
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # ➡️ MICROSERVICIO 1: Envía todo lo que vaya a /api/despachos al puerto 8085
    location /api/despachos {
        # Reescribe la ruta quitando la palabra '/api/despachos' para que a Spring Boot le llegue limpio
        rewrite ^/api/despachos/(.*)$ /api/$1 break;

        proxy_pass http://10.0.134.21:8085;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    # ➡️ MICROSERVICIO 2: Envía todo lo que vaya a /api/ventas al puerto 8086
    location /api/ventas {
        # Reescribe la ruta quitando la palabra '/api/ventas' para que a Spring Boot le llegue limpio
        rewrite ^/api/ventas/(.*)$ /api/$1 break;

        proxy_pass http://10.0.134.21:8086;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}