server {
    listen 80;
    server_name localhost;

    # Sirve los archivos estáticos de React
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # REVERSE PROXY: Mantiene el /api/ explícitamente en el destino
    location /api/ {
        # ➡️ CONFIGURACIÓN UNIVERSAL: Añadimos /api al final de la ruta proxy
        # Si el front busca /api/v1/despachos, Nginx lo manda a http://10.0.134.21:8085/api/v1/despachos
        proxy_pass http://10.0.134.21:8085/api/;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}