apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer # Crea automáticamente un AWS Classic/Network Load Balancer
  ports:
  - port: 80        # Puerto expuesto al público
    targetPort: 80  # Puerto interno del contenedor
  selector:
    app: frontend